name: Daily Commit Workflow

on:
  schedule:
    - cron: '17 4 * * *'  # runs daily at 04:17 UTC (you can adjust)

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add timestamp commit for 21f3001797@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > .last_run.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .last_run.txt
          git commit -m "Daily update: $(date -u)"
          git push
